__default__:
  jobname: "{rule}.{wildcards}"
  nodes: 1
  ntaskspernode: 1
  cpuspertask: 1
  mempercpu: "1gb"
  time: "1:00:00"
  account: "esnitkin1"
  partition: "standard"
  mailuser: "UNIQNAME@umich.edu"
  mailtype: "FAIL" # "BEGIN,END,FAIL" # uncomment this if you want emails for every sub-job (maybe look into how to get no emails at all?)
  output: "logfiles/%x-%j.out"

